#!/usr/bin/env python3
"""
Demo chart: Top 5 Python Data Visualization Libraries by GitHub Stars
Research Date: 2025
Generated by Bob (Mind Clone AI Agent) - Autonomous Agent Demonstration
"""

import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt

# Top 5 Python Data Visualization Libraries by GitHub stars (2025 estimates)
# Based on web research - Matplotlib leads as the foundational library
libraries = ['Matplotlib', 'Plotly', 'Bokeh', 'Seaborn', 'Altair']
stars = [20000, 18000, 14000, 12000, 8000]  # Estimated 2025 numbers

# Create bar chart
fig, ax = plt.subplots(figsize=(12, 7))
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
bars = ax.bar(libraries, stars, color=colors, edgecolor='black', linewidth=1.5)

# Add value labels on bars
for bar, star in zip(bars, stars):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 300,
            f'{star:,} stars', ha='center', va='bottom', fontsize=12, fontweight='bold')

# Customize
ax.set_xlabel('Python Library', fontsize=14, fontweight='bold')
ax.set_ylabel('GitHub Stars (Estimated)', fontsize=14, fontweight='bold')
ax.set_title('Top 5 Python Data Visualization Libraries by GitHub Stars (2025)\nGenerated Autonomously by Bob AI Agent',
             fontsize=14, fontweight='bold', pad=20)
ax.yaxis.grid(True, linestyle='--', alpha=0.7)
ax.set_axisbelow(True)
ax.set_ylim(0, 24000)
ax.set_facecolor('#f8f9fa')

# Add source note
fig.text(0.5, 0.02, 'Data source: Web research on Python visualization libraries | Chart generated autonomously',
         ha='center', fontsize=9, style='italic', color='gray')

plt.tight_layout()
plt.savefig('demo_chart.png', dpi=150, bbox_inches='tight', facecolor='white')
print('SUCCESS: Chart saved as demo_chart.png')
print('Libraries visualized:', ', '.join(libraries))
