# SECTION 11: FASTAPI APPLICATION
# ============================================================================
#
# This file now re-exports everything from the shared/ package for backward
# compatibility. All implementation has moved to:
#   shared/constants.py  -- config values and env vars
#   shared/state.py      -- runtime state, background tasks, locks
#   shared/imports.py    -- service imports with fallback stubs
#   shared/helpers.py    -- utility functions, lifespan, serializers
#

from .shared import *  # noqa: F401,F403
from .shared import (  # explicit re-exports for type checkers
    _env_flag,
    _candidate_node_scores,
    _count_workflow_actions,
    _ensure_team_agent_owner,
    _normalize_capability_list,
    _refresh_node_runtime_metrics,
    _resolve_identity_owner,
    _safe_json_dict,
    _safe_json_list,
    _upsert_identity_link,
    _validate_checkpoint_replay_state,
    _workflow_eval_condition,
    _workflow_render_template,
    app_lifespan,
    get_db,
    require_ops_auth,
    record_ops_audit_event,
    iso_datetime_or_none,
    resolve_ui_user_context,
    serialize_task_summary,
    serialize_pending_approval,
    list_pending_approvals_for_owner,
    resolve_root_ui_user_context,
    get_team_agent_with_user,
    serialize_team_agent,
    list_team_agents_for_owner,
    resolve_team_agent_owner_for_request,
    parse_workflow_program_text,
    memory_vault_bootstrap,
    memory_vault_backup,
    memory_vault_restore,
    ui_dist_ready,
    ui_not_built_response,
    resolve_ui_asset_path,
    parse_task_command_payload,
    parse_cron_add_payload,
    RUNTIME_STATE,
    TELEGRAM_BOT_TOKEN,
    TOKEN_PLACEHOLDER,
    TASK_STATUS_QUEUED,
    TEAM_MODE_ENABLED,
    TEAM_AGENT_DEFAULT_KEY,
    TEAM_BROADCAST_ENABLED,
    WORKFLOW_V2_ENABLED,
    WORKFLOW_MAX_STEPS,
    EVAL_MAX_CASES,
    EVENT_STREAM_POLL_SECONDS,
    EVENT_STREAM_BATCH_SIZE,
    BLACKBOX_ENABLED,
    NODE_CONTROL_PLANE_ENABLED,
    HEARTBEAT_AUTONOMY_ENABLED,
    CRON_ENABLED,
    IDENTITY_SCOPE_MODE,
    OPS_AUTH_ENABLED,
    OPS_AUTH_TOKEN,
    CANARY_ROUTER_ENABLED,
    CANARY_STATE,
    logger,
    log,
    SessionLocal,
    Task,
    User,
    TeamAgent,
    ApprovalRequest,
    ScheduledJob,
    Goal,
    OpsAuditEvent,
    UsageLedger,
    WorkflowProgram,
    NodeRegistration,
    NodeLease,
    HostExecGrant,
    IdentityLink,
    IdentityKernel,
    ConversationMessage,
    ConversationSummary,
    TaskDeadLetter,
    TaskArtifact,
    TaskCheckpointSnapshot,
    ResearchNote,
    ActionForecast,
    SelfImprovementNote,
    EpisodicMemory,
    ToolPerformanceLog,
    GeneratedTool,
    CapabilityActivation,
    ExecutionEvent,
    MemoryVector,
    SchemaMigration,
)
